

/**
 * +2 vs defender's back
 * +4 vs prone defender
 * -2 medium range
 * -5 long range
 */
export const weaponTable = [
  {
    weaponType: "arrow",
    weight: 2,
    damageVsSmall: "1d6",
    damageVsLarge: "1d6"
  }, {
    weaponType: "composite longbow",
    fireRate: 2,
    shortRange: 6,
    mediumRange: 12,
    longRange: 21,
    armorClassAdjustment: {
      ac2: -2,
      ac3: -1,
      ac4: 0,
      ac5: 0,
      ac6: 1,
      ac7: 2,
      ac8: 2,
      ac9: 3,
      ac10: 3
    }
  }, {
    weaponType: "composite shortbow",
    fireRate: 2,
    shortRange: 5,
    mediumRange: 10,
    longRange: 18,
    armorClassAdjustment: {
      ac2: -3,
      ac3: -3,
      ac4: -1,
      ac5: 0,
      ac6: 1,
      ac7: 2,
      ac8: 2,
      ac9: 2,
      ac10: 3
    }
  }, {
    weaponType: "longbow",
    fireRate: 2,
    shortRange: 7,
    mediumRange: 14,
    longRange: 21,
    armorClassAdjustment: {
      ac2: -1,
      ac3: 0,
      ac4: 0,
      ac5: 1,
      ac6: 2,
      ac7: 3,
      ac8: 3,
      ac9: 3,
      ac10: 3
    }
  }, {
    weaponType: "shortbow",
    fireRate: 2,
    shortRange: 5,
    mediumRange: 10,
    longRange: 15,
    armorClassAdjustment: {
      ac2: -5,
      ac3: -4,
      ac4: -1,
      ac5: 0,
      ac6: 0,
      ac7: 1,
      ac8: 2,
      ac9: 2,
      ac10: 2
    }
  }, {
    weaponType: "battle axe",
    weight: 75,
    damageVsSmall: "1d8",
    damageVsLarge: "1d8",
    length: 4,
    spaceRequired: 4,
    speedFactor: 7,
    armorClassAdjustment: {
      ac2: -3,
      ac3: -2,
      ac4: -1,
      ac5: -1,
      ac6: 0,
      ac7: 0,
      ac8: 1,
      ac9: 1,
      ac10: 2
    }
  }, {
    weaponType: "hand axe",
    weight: 50,
    damageVsSmall: "1d6",
    damageVsLarge: "1d4",
    length: 1.5,
    spaceRequired: 1,
    speedFactor: 4,
    armorClassAdjustment: {
      ac2: -3,
      ac3: -2,
      ac4: -2,
      ac5: -1,
      ac6: 0,
      ac7: 0,
      ac8: 1,
      ac9: 1,
      ac10: 1
    }
  }, {
    weaponType: "thrown axe",
    weight: 50,
    damageVsSmall: "1d6",
    damageVsLarge: "1d4",
    length: 1.5,
    spaceRequired: 1,
    fireRate: 1,
    shortRange: 1,
    mediumRange: 2,
    longRange: 3,
    armorClassAdjustment: {
      ac2: -4,
      ac3: -3,
      ac4: -2,
      ac5: -1,
      ac6: -1,
      ac7: 0,
      ac8: 0,
      ac9: 0,
      ac10: 1
    }
  }, {
    weaponType: "bardiche",
    weight: 125,
    damageVsSmall: "2d4",
    damageVsLarge: "3d4",
    length: 5,
    spaceRequired: 5,
    speedFactor: 9,
    armorClassAdjustment: {
      ac2: -2,
      ac3: -1,
      ac4: 0,
      ac5: 0,
      ac6: 1,
      ac7: 1,
      ac8: 2,
      ac9: 2,
      ac10: 3
    }
  }, {
    weaponType: "bec de corbin",
    weight: 100,
    damageVsSmall: "1d8",
    damageVsLarge: "1d6",
    length: 6,
    spaceRequired: 6,
    speedFactor: 9,
    armorClassAdjustment: {
      ac2: 2,
      ac3: 2,
      ac4: 2,
      ac5: 0,
      ac6: 0,
      ac7: 0,
      ac8: 0,
      ac9: 0,
      ac10: -1
    }
  }, {
    weaponType: "bill-guisarme",
    weight: 150,
    damageVsSmall: "2d4",
    damageVsLarge: "1d10",
    length: 8,
    spaceRequired: 2,
    speedFactor: 10,
    armorClassAdjustment: {
      ac2: 0,
      ac3: 0,
      ac4: 0,
      ac5: 0,
      ac6: 0,
      ac7: 0,
      ac8: 1,
      ac9: 0,
      ac10: 0
    }
  }, {
    weaponType: "bo stick",
    weight: 15,
    damageVsSmall: "1d6",
    damageVsLarge: "1d3",
    length: 5,
    spaceRequired: 3,
    speedFactor: 3,
    armorClassAdjustment: {
      ac2: -9,
      ac3: -7,
      ac4: -5,
      ac5: -3,
      ac6: -1,
      ac7: 0,
      ac8: 1,
      ac9: 0,
      ac10: 3
    }
  }, {
    weaponType: "club",
    weight: 30,
    damageVsSmall: "1d6",
    damageVsLarge: "1d3",
    length: 3,
    spaceRequired: 3,
    speedFactor: 4,
    armorClassAdjustment: {
      ac2: -5,
      ac3: -4,
      ac4: -3,
      ac5: -2,
      ac6: -1,
      ac7: -1,
      ac8: 0,
      ac9: 0,
      ac10: 1
    }
  }, {
    weaponType: "thrown club",
    weight: 30,
    damageVsSmall: "1d6",
    damageVsLarge: "1d3",
    length: 3,
    spaceRequired: 3,
    fireRate: 1,
    shortRange: 1,
    mediumRange: 2,
    longRange: 3,
    armorClassAdjustment: {
      ac2: -7,
      ac3: -5,
      ac4: -3,
      ac5: -2,
      ac6: -1,
      ac7: -1,
      ac8: -1,
      ac9: 0,
      ac10: 0
    }
  }, {
    weaponType: "dagger",
    weight: 10,
    damageVsSmall: "1d4",
    damageVsLarge: "1d3",
    length: 1.25,
    spaceRequired: 1,
    speedFactor: 2,
    armorClassAdjustment: {
      ac2: -3,
      ac3: -3,
      ac4: -2,
      ac5: -2,
      ac6: 0,
      ac7: 0,
      ac8: 1,
      ac9: 1,
      ac10: 3
    }
  }, {
    weaponType: "thrown dagger",
    weight: 10,
    damageVsSmall: "1d4",
    damageVsLarge: "1d3",
    length: 1.25,
    spaceRequired: 1,
    fireRate: 2,
    shortRange: 1,
    mediumRange: 12,
    longRange: 3,
    armorClassAdjustment: {
      ac2: -5,
      ac3: -4,
      ac4: -3,
      ac5: -2,
      ac6: -1,
      ac7: -1,
      ac8: 0,
      ac9: 0,
      ac10: 1
    }
  }, {
    weaponType: "dart",
    weight: 5,
    damageVsSmall: "1d4",
    damageVsLarge: "1d3",
    fireRate: 3,
    shortRange: 1.5,
    mediumRange: 3,
    longRange: 4.5,
    armorClassAdjustment: {
      ac2: -5,
      ac3: -4,
      ac4: -3,
      ac5: -2,
      ac6: -1,
      ac7: 0,
      ac8: 1,
      ac9: 0,
      ac10: 1
    }
  }, {
    weaponType: "fauchard",
    weight: 60,
    damageVsSmall: "1d6",
    damageVsLarge: "1d8",
    length: 8,
    spaceRequired: 2,
    speedFactor: 8,
    armorClassAdjustment: {
      ac2: -2,
      ac3: -2,
      ac4: -1,
      ac5: -1,
      ac6: 0,
      ac7: 0,
      ac8: 0,
      ac9: -1,
      ac10: -1
    },
    dismountRider: true
  }, {
    weaponType: "fauchard fork",
    weight: 80,
    damageVsSmall: "1d8",
    damageVsLarge: "1d10",
    length: 8,
    spaceRequired: 2,
    speedFactor: 8,
    armorClassAdjustment: {
      ac2: -1,
      ac3: -1,
      ac4: -1,
      ac5: 0,
      ac6: 0,
      ac7: 0,
      ac8: 1,
      ac9: 0,
      ac10: 1
    },
    dismountRider: true
  }, {
    weaponType: "fist",
    length: 2,
    spaceRequired: 0,
    speedFactor: 1,
    armorClassAdjustment: {
      ac2: -7,
      ac3: -5,
      ac4: -3,
      ac5: -1,
      ac6: 0,
      ac7: 0,
      ac8: 2,
      ac9: 0,
      ac10: 4
    }
  }, {
    weaponType: "footman's flail",
    weight: 150,
    damageVsSmall: "1d6+1",
    damageVsLarge: "2d4",
    length: 4,
    spaceRequired: 6,
    speedFactor: 7,
    armorClassAdjustment: {
      ac2: 2,
      ac3: 2,
      ac4: 1,
      ac5: 2,
      ac6: 1,
      ac7: 1,
      ac8: 1,
      ac9: 1,
      ac10: -1
    }
  }, {
    weaponType: "horseman's flail",
    weight: 35,
    damageVsSmall: "1d4+1",
    damageVsLarge: "1d4+1",
    length: 2,
    spaceRequired: 4,
    speedFactor: 6,
    armorClassAdjustment: {
      ac2: 0,
      ac3: 0,
      ac4: 0,
      ac5: 0,
      ac6: 0,
      ac7: 1,
      ac8: 1,
      ac9: 1,
      ac10: 0
    }
  }, {
    weaponType: "military fork",
    weight: 75,
    damageVsSmall: "1d8",
    damageVsLarge: "2d4",
    doubleDamageVsLargeWhenSet: true,
    length: 7,
    spaceRequired: 1,
    speedFactor: 7,
    armorClassAdjustment: {
      ac2: -2,
      ac3: -2,
      ac4: -1,
      ac5: 0,
      ac6: 0,
      ac7: 1,
      ac8: 1,
      ac9: 0,
      ac10: 1
    },
    dismountRider: true
  }, {
    weaponType: "glaive",
    weight: 75,
    damageVsSmall: "1d6",
    damageVsLarge: "1d10",
    doubleDamageVsLargeWhenSet: true,
    length: 8,
    spaceRequired: 1,
    speedFactor: 8,
    armorClassAdjustment: {
      ac2: -1,
      ac3: -1,
      ac4: 0,
      ac5: 0,
      ac6: 0,
      ac7: 0,
      ac8: 0,
      ac9: 0,
      ac10: 0
    }
  }, {
    weaponType: "glaive guisarme",
    weight: 100,
    damageVsSmall: "2d4",
    damageVsLarge: "2d6",
    doubleDamageVsLargeWhenSet: true,
    length: 8,
    spaceRequired: 1,
    speedFactor: 9,
    armorClassAdjustment: {
      ac2: -1,
      ac3: -1,
      ac4: 0,
      ac5: 0,
      ac6: 0,
      ac7: 0,
      ac8: 0,
      ac9: 0,
      ac10: 0
    },
    dismountRider: true
  }, {
    weaponType: "guisarme",
    weight: 80,
    damageVsSmall: "2d4",
    damageVsLarge: "1d8",
    length: 6,
    spaceRequired: 2,
    speedFactor: 8,
    armorClassAdjustment: {
      ac2: -2,
      ac3: -2,
      ac4: -1,
      ac5: -1,
      ac6: 0,
      ac7: 0,
      ac8: 0,
      ac9: -1,
      ac10: -1
    },
    dismountRider: true
  }, {
    weaponType: "guisarme-voulge",
    weight: 150,
    damageVsSmall: "2d4",
    damageVsLarge: "2d4",
    length: 7,
    spaceRequired: 2,
    speedFactor: 10,
    armorClassAdjustment: {
      ac2: -1,
      ac3: -1,
      ac4: 0,
      ac5: 1,
      ac6: 1,
      ac7: 1,
      ac8: 0,
      ac9: 0,
      ac10: 0
    },
    dismountRider: true
  }, {
    weaponType: "halberd",
    weight: 175,
    damageVsSmall: "1d10",
    damageVsLarge: "2d6",
    length: 5,
    spaceRequired: 5,
    speedFactor: 9,
    armorClassAdjustment: {
      ac2: 1,
      ac3: 1,
      ac4: 1,
      ac5: 2,
      ac6: 2,
      ac7: 2,
      ac8: 1,
      ac9: 1,
      ac10: 0
    }
  }, {
    weaponType: "lucerne hammer",
    weight: 150,
    damageVsSmall: "2d4",
    damageVsLarge: "1d6",
    length: 5,
    spaceRequired: 5,
    speedFactor: 9,
    armorClassAdjustment: {
      ac2: 1,
      ac3: 1,
      ac4: 2,
      ac5: 2,
      ac6: 2,
      ac7: 1,
      ac8: 1,
      ac9: 0,
      ac10: 0
    },
    dismountRider: true
  }, {
    weaponType: "hammer",
    weight: 50,
    damageVsSmall: "1d4+1",
    damageVsLarge: "1d4",
    length: 1.5,
    spaceRequired: 2,
    speedFactor: 4,
    armorClassAdjustment: {
      ac2: 0,
      ac3: 1,
      ac4: 0,
      ac5: 1,
      ac6: 0,
      ac7: 0,
      ac8: 0,
      ac9: 0,
      ac10: 0
    }
  }, {
    weaponType: "thrown hammer",
    weight: 50,
    damageVsSmall: "1d4+1",
    damageVsLarge: "1d4",
    length: 1.5,
    spaceRequired: 2,
    fireRate: 1,
    shortRange: 1,
    mediumRange: 2,
    longRange: 3,
    armorClassAdjustment: {
      ac2: -2,
      ac3: -1,
      ac4: 0,
      ac5: 0,
      ac6: 0,
      ac7: 0,
      ac8: 0,
      ac9: 0,
      ac10: 1
    }
  }, {
    weaponType: "javelin",
    weight: 20,
    damageVsSmall: "1d6",
    damageVsLarge: "1d6",
    doubleDamageVsLargeWhenSet: true,
    fireRate: 1,
    shortRange: 2,
    mediumRange: 4,
    longRange: 6,
    armorClassAdjustment: {
      ac2: -5,
      ac3: -4,
      ac4: -3,
      ac5: -2,
      ac6: -1,
      ac7: 0,
      ac8: 1,
      ac9: 0,
      ac10: 1
    }
  }, {
    weaponType: "jo stick",
    weight: 40,
    damageVsSmall: "1d6",
    damageVsLarge: "1d4",
    length: 3,
    spaceRequired: 2,
    speedFactor: 2,
    armorClassAdjustment: {
      ac2: -8,
      ac3: -6,
      ac4: -4,
      ac5: -2,
      ac6: -1,
      ac7: 0,
      ac8: 1,
      ac9: 0,
      ac10: 2
    }
  }, {
    weaponType: "light horse lance",
    weight: 50,
    damageVsSmall: "1d6",
    damageVsLarge: "1d8",
    doubleDamageVsChargingMount: true,
    length: 10,
    spaceRequired: 1,
    speedFactor: 7,
    armorClassAdjustment: {
      ac2: -2,
      ac3: -2,
      ac4: -1,
      ac5: 0,
      ac6: 0,
      ac7: 0,
      ac8: 0,
      ac9: 0,
      ac10: 0
    }
  }, {
    weaponType: "medium horse lance",
    weight: 100,
    damageVsSmall: "1d6+1",
    damageVsLarge: "2d6",
    doubleDamageVsChargingMount: true,
    length: 12,
    spaceRequired: 1,
    speedFactor: 6,
    armorClassAdjustment: {
      ac2: 0,
      ac3: 1,
      ac4: 1,
      ac5: 1,
      ac6: 1,
      ac7: 0,
      ac8: 0,
      ac9: 0,
      ac10: 0
    }
  }, {
    weaponType: "heavy horse lance",
    weight: 150,
    damageVsSmall: "2d4+1",
    damageVsLarge: "3d6",
    doubleDamageVsChargingMount: true,
    length: 14,
    spaceRequired: 1,
    speedFactor: 8,
    armorClassAdjustment: {
      ac2: 3,
      ac3: 3,
      ac4: 2,
      ac5: 2,
      ac6: 2,
      ac7: 1,
      ac8: 1,
      ac9: 0,
      ac10: 0
    }
  }, {
    weaponType: "footman's mace",
    weight: 100,
    damageVsSmall: "1d6+1",
    damageVsLarge: "1d6",
    length: 2.5,
    spaceRequired: 4,
    speedFactor: 7,
    armorClassAdjustment: {
      ac2: 1,
      ac3: 1,
      ac4: 0,
      ac5: 0,
      ac6: 0,
      ac7: 0,
      ac8: 0,
      ac9: 1,
      ac10: -1
    }
  }, {
    weaponType: "horseman's mace",
    weight: 50,
    damageVsSmall: "1d6",
    damageVsLarge: "1d4",
    length: 1.5,
    spaceRequired: 2,
    speedFactor: 6,
    armorClassAdjustment: {
      ac2: 1,
      ac3: 1,
      ac4: 0,
      ac5: 0,
      ac6: 0,
      ac7: 0,
      ac8: 0,
      ac9: 0,
      ac10: 0
    }
  }, {
    weaponType: "morning star",
    weight: 125,
    damageVsSmall: "2d4",
    damageVsLarge: "1d6+1",
    length: 4,
    spaceRequired: 5,
    speedFactor: 7,
    armorClassAdjustment: {
      ac2: 0,
      ac3: 1,
      ac4: 1,
      ac5: 1,
      ac6: 1,
      ac7: 1,
      ac8: 1,
      ac9: 2,
      ac10: 2
    }
  }, {
    weaponType: "partisan",
    weight: 80,
    damageVsSmall: "1d6",
    damageVsLarge: "1d6+1",
    length: 7,
    spaceRequired: 3,
    speedFactor: 9,
    armorClassAdjustment: {
      ac2: 0,
      ac3: 0,
      ac4: 0,
      ac5: 0,
      ac6: 0,
      ac7: 0,
      ac8: 0,
      ac9: 0,
      ac10: 0
    }
  }, {
    weaponType: "footman's military pick",
    weight: 60,
    damageVsSmall: "1d6+1",
    damageVsLarge: "2d4",
    length: 4,
    spaceRequired: 4,
    speedFactor: 7,
    armorClassAdjustment: {
      ac2: 2,
      ac3: 2,
      ac4: 1,
      ac5: 1,
      ac6: 0,
      ac7: -1,
      ac8: -1,
      ac9: -1,
      ac10: -2
    }
  }, {
    weaponType: "horseman's military pick",
    weight: 40,
    damageVsSmall: "1d4+1",
    damageVsLarge: "1d4",
    length: 2,
    spaceRequired: 2,
    speedFactor: 5,
    armorClassAdjustment: {
      ac2: 1,
      ac3: 1,
      ac4: 1,
      ac5: 1,
      ac6: 0,
      ac7: 0,
      ac8: -1,
      ac9: -1,
      ac10: -1
    }
  }, {
    weaponType: "awl pike",
    weight: 80,
    damageVsSmall: "1d6",
    damageVsLarge: "1d12",
    length: 18,
    spaceRequired: 1,
    speedFactor: 13,
    armorClassAdjustment: {
      ac2: -1,
      ac3: 0,
      ac4: 0,
      ac5: 0,
      ac6: 0,
      ac7: 0,
      ac8: 0,
      ac9: -1,
      ac10: -2
    }
  }, {
    weaponType: "light quarrel",
    weight: 1,
    damageVsSmall: "1d4",
    damageVsLarge: "1d4"
  }, {
    weaponType: "heavy quarrel",
    weight: 2,
    damageVsSmall: "1d4+1",
    damageVsLarge: "1d6+1"
  }, {
    weaponType: "heavy crossbow",
    fireRate: .5,
    shortRange: 8,
    mediumRange: 16,
    longRange: 24,
    armorClassAdjustment: {
      ac2: -1,
      ac3: 0,
      ac4: 1,
      ac5: 2,
      ac6: 3,
      ac7: 3,
      ac8: 4,
      ac9: 4,
      ac10: 4
    }
  }, {
    weaponType: "light crossbow",
    fireRate: 1,
    shortRange: 6,
    mediumRange: 12,
    longRange: 18,
    armorClassAdjustment: {
      ac2: -2,
      ac3: -1,
      ac4: 0,
      ac5: 0,
      ac6: 1,
      ac7: 2,
      ac8: 3,
      ac9: 3,
      ac10: 3
    }
  }, {
    weaponType: "ranseur",
    weight: 50,
    damageVsSmall: "2d4",
    damageVsLarge: "2d4",
    length: 8,
    spaceRequired: 1,
    speedFactor: 8,
    armorClassAdjustment: {
      ac2: -2,
      ac3: -1,
      ac4: -1,
      ac5: 0,
      ac6: 0,
      ac7: 0,
      ac8: 0,
      ac9: 0,
      ac10: 1
    },
    dismountRider: true
  }, {
    weaponType: "scimitar",
    weight: 40,
    damageVsSmall: "1d8",
    damageVsLarge: "1d8",
    length: 3,
    spaceRequired: 2,
    speedFactor: 4,
    armorClassAdjustment: {
      ac2: -3,
      ac3: -2,
      ac4: -2,
      ac5: -1,
      ac6: 0,
      ac7: 0,
      ac8: 1,
      ac9: 1,
      ac10: 3
    }
  }, {
    weaponType: "sling bullet",
    weight: 2,
    damageVsSmall: "1d4+1",
    damageVsLarge: "1d6+1",
    fireRate: 1,
    shortRange: 5,
    mediumRange: 10,
    longRange: 20,
    armorClassAdjustment: {
      ac2: -2,
      ac3: -2,
      ac4: -1,
      ac5: 0,
      ac6: 0,
      ac7: 0,
      ac8: 2,
      ac9: 1,
      ac10: 3
    }
  }, {
    weaponType: "sling stone",
    weight: 1,
    damageVsSmall: "1d4",
    damageVsLarge: "1d4",
    fireRate: 1,
    shortRange: 4,
    mediumRange: 8,
    longRange: 16,
    armorClassAdjustment: {
      ac2: -5,
      ac3: -4,
      ac4: -2,
      ac5: -1,
      ac6: 0,
      ac7: 0,
      ac8: 2,
      ac9: 1,
      ac10: 3
    }
  }, {
    weaponType: "spear",
    weight: 50,
    damageVsSmall: "1d6",
    damageVsLarge: "1d8",
    doubleDamageWhenSet: true,
    length: 9,
    spaceRequired: 1,
    speedFactor: 7,
    armorClassAdjustment: {
      ac2: -2,
      ac3: -1,
      ac4: -1,
      ac5: -1,
      ac6: 0,
      ac7: 0,
      ac8: 0,
      ac9: 0,
      ac10: 0
    }
  }, {
    weaponType: "thrown spear",
    weight: 50,
    damageVsSmall: "1d6",
    damageVsLarge: "1d8",
    doubleDamageWhenSet: true,
    length: 9,
    spaceRequired: 1,
    fireRate: 1,
    shortRange: 1,
    mediumRange: 2,
    longRange: 3,
    armorClassAdjustment: {
      ac2: -3,
      ac3: -3,
      ac4: -2,
      ac5: -2,
      ac6: -1,
      ac7: 0,
      ac8: 0,
      ac9: 0,
      ac10: 0
    }
  }, {
    weaponType: "spetum",
    weight: 50,
    damageVsSmall: "1d6+1",
    damageVsLarge: "2d6",
    length: 8,
    spaceRequired: 1,
    speedFactor: 8,
    armorClassAdjustment: {
      ac2: -2,
      ac3: -1,
      ac4: 0,
      ac5: 0,
      ac6: 0,
      ac7: 0,
      ac8: 0,
      ac9: 1,
      ac10: 2
  },
    disarmVsAc8: true
  }, {
    weaponType: "quarterstaff",
    weight: 50,
    damageVsSmall: "1d6",
    damageVsLarge: "1d6",
    length: 7,
    spaceRequired: 3,
    speedFactor: 4,
    armorClassAdjustment: {
      ac2: -7,
      ac3: -5,
      ac4: -3,
      ac5: -1,
      ac6: 0,
      ac7: 0,
      ac8: 1,
      ac9: 1,
      ac10: 1
    }
  }, {
    weaponType: "bastard sword", // treat as long sword if used one-handed
    weight: 100,
    damageVsSmall: "2d4",
    damageVsLarge: "2d8",
    length: 4.5,
    spaceRequired: 4,
    speedFactor: 6,
    armorClassAdjustment: {
      ac2: 0,
      ac3: 0,
      ac4: 1,
      ac5: 1,
      ac6: 1,
      ac7: 1,
      ac8: 1,
      ac9: 1,
      ac10: 0
    },
  }, {
    weaponType: "broadsword",
    weight: 75,
    damageVsSmall: "2d4",
    damageVsLarge: "1d6+1",
    length: 3.5,
    spaceRequired: 4,
    speedFactor: 5,
    armorClassAdjustment: {
      ac2: -3,
      ac3: -2,
      ac4: -1,
      ac5: 0,
      ac6: 0,
      ac7: 1,
      ac8: 1,
      ac9: 1,
      ac10: 2
    }
  }, {
    weaponType: "longsword",
    weight: 60,
    damageVsSmall: "1d8",
    damageVsLarge: "1d12",
    length: 3.5,
    spaceRequired: 3,
    speedFactor: 5,
    armorClassAdjustment: {
      ac2: -2,
      ac3: -1,
      ac4: 0,
      ac5: 0,
      ac6: 0,
      ac7: 0,
      ac8: 0,
      ac9: 1,
      ac10: 2
    }
  }, {
    weaponType: "shortsword",
    weight: 35,
    damageVsSmall: "1d6",
    damageVsLarge: "1d8",
    length: 2,
    spaceRequired: 1,
    speedFactor: 3,
    armorClassAdjustment: {
      ac2: -3,
      ac3: -2,
      ac4: -1,
      ac5: 0,
      ac6: 0,
      ac7: 0,
      ac8: 1,
      ac9: 0,
      ac10: 2
    }
  }, {
    weaponType: "two handed sword",
    weight: 250,
    damageVsSmall: "1d10",
    damageVsLarge: "3d6",
    length: 6,
    spaceRequired: 6,
    speedFactor: 10,
    armorClassAdjustment: {
      ac2: 2,
      ac3: 2,
      ac4: 2,
      ac5: 2,
      ac6: 3,
      ac7: 3,
      ac8: 3,
      ac9: 1,
      ac10: 0
    }
  }, {
    weaponType: "trident",
    weight: 50,
    damageVsSmall: "1d6+1",
    damageVsLarge: "3d4",
    length: 6,
    spaceRequired: 1,
    speedFactor: 7,
    armorClassAdjustment: {
      ac2: -3,
      ac3: -2,
      ac4: -1,
      ac5: -1,
      ac6: 0,
      ac7: 0,
      ac8: 1,
      ac9: 0,
      ac10: 1
    }
  }, {
    weaponType: "voulge",
    weight: 125,
    damageVsSmall: "2d4",
    damageVsLarge: "2d4",
    length: 8,
    spaceRequired: 2,
    speedFactor: 10,
    armorClassAdjustment: {
      ac2: -1,
      ac3: -1,
      ac4: 0,
      ac5: 1,
      ac6: 1,
      ac7: 1,
      ac8: 0,
      ac9: 0,
      ac10: 0
    }
  }
];