export const charismaTable = [
  {
    score: 3,
    maxHenchmen: 1,
    loyalty: -30,
    reaction: -25
  }, {
    score: 4,
    maxHenchmen: 1,
    loyalty: -25,
    reaction: -20
  }, {
    score: 5,
    maxHenchmen: 2,
    loyalty: -20,
    reaction: -15
  }, {
    score: 6,
    maxHenchmen: 2,
    loyalty: -15,
    reaction: -10
  }, {
    score: 7,
    maxHenchmen: 3,
    loyalty: -10,
    reaction: -5
  }, {
    score: 8,
    maxHenchmen: 3,
    loyalty: -5,
    reaction: 0
  }, {
    score: 9,
    maxHenchmen: 4,
    loyalty: 0,
    reaction: 0
  }, {
    score: 10,
    maxHenchmen: 4,
    loyalty: 0,
    reaction: 0
  }, {
    score: 11,
    maxHenchmen: 4,
    loyalty: 0,
    reaction: 0
  }, {
    score: 12,
    maxHenchmen: 5,
    loyalty: 0,
    reaction: 0
  }, {
    score: 13,
    maxHenchmen: 5,
    loyalty: 0,
    reaction: 5
  }, {
    score: 14,
    maxHenchmen: 6,
    loyalty: 5,
    reaction: 10
  }, {
    score: 15,
    maxHenchmen: 7,
    loyalty: 15,
    reaction: 15
  }, {
    score: 16,
    maxHenchmen: 8,
    loyalty: 20,
    reaction: 25
  }, {
    score: 17,
    maxHenchmen: 10,
    loyalty: 30,
    reaction: 30
  }, {
    score: 18,
    maxHenchmen: 15,
    loyalty: 40,
    reaction: 35
  }
];