export const intelligenceTable = [
  {
    min: 8,
    max: 8,
    additionalLanguages: 1
  }, {
    min: 9,
    max: 9,
    additionalLanguages: 1,
    knowSpell: 35,
    minSpellsPerLevel: 4,
    maxSpellsPerLevel: 6
  }, {
    min: 10,
    max: 11,
    additionalLanguages: 2,
    knowSpell: 45,
    minSpellsPerLevel: 5,
    maxSpellsPerLevel: 7
  }, {
    min: 12,
    max: 12,
    additionalLanguages: 3,
    knowSpell: 45,
    minSpellsPerLevel: 5,
    maxSpellsPerLevel: 7
  }, {
    min: 13,
    max: 13,
    additionalLanguages: 3,
    knowSpell: 55,
    minSpellsPerLevel: 6,
    maxSpellsPerLevel: 9
  }, {
    min: 14,
    max: 14,
    additionalLanguages: 4,
    knowSpell: 55,
    minSpellsPerLevel: 6,
    maxSpellsPerLevel: 9
  }, {
    min: 15,
    max: 15,
    additionalLanguages: 4,
    knowSpell: 65,
    minSpellsPerLevel: 7,
    maxSpellsPerLevel: 11
  }, {
    min: 16,
    max: 16,
    additionalLanguages: 5,
    knowSpell: 65,
    minSpellsPerLevel: 7,
    maxSpellsPerLevel: 11
  }, {
    min: 17,
    max: 17,
    additionalLanguages: 6,
    knowSpell: 75,
    minSpellsPerLevel: 8,
    maxSpellsPerLevel: 14
  }, {
    min: 18,
    max: 18,
    additionalLanguages: 7,
    knowSpell: 85,
    minSpellsPerLevel: 9,
    maxSpellsPerLevel: 18
  }, {
    min: 19,
    max: Infinity,
    additionalLanguages: 7,
    knowSpell: 95,
    minSpellsPerLevel: 10,
    maxSpellsPerLevel: Infinity
  }
];